# Docker compose file to setup and run development environment

version: "3.8"

networks:
  main:

services:
  k-chat:
    container_name: k-chat
    build: ./
    image: k-chat:dev
    depends_on: [postgresql, rabbitmq]
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      PG_DB_CONNECTION: postgre://postgres:4444@k-chat-postgresql:5432/k-chat
      RABBITMQ_CONNECTION: amqp://k-chat-rabbitmq
    networks:
      main:
        aliases:
          - k-chat
  postgresql:
    container_name: k-chat-postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: 4444
      POSTGRES_DB: k-chat
    ports:
      - 6543:5432
    networks:
      main:
        aliases:
          - k-chat-postgresql
  rabbitmq:
    image: rabbitmq
    container_name: k-chat-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      main:
        aliases:
          - k-chat-rabbitmq
